apiVersion: v1
kind: Service
metadata:
  name: kubeapp-ecr-clb
  labels:
    app: kubeapp-ecr
spec:
  type: LoadBalancer
  selector:
    app: kubeapp-ecr
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
