apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: med-rag
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/part-of: ai-korean-medi-rag
spec:
  serviceName: qdrant
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: qdrant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qdrant
        app.kubernetes.io/part-of: ai-korean-medi-rag
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.11.3
          ports:
            - name: http
              containerPort: 6333
            - name: grpc
              containerPort: 6334
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          readinessProbe:
            tcpSocket:
              port: 6333
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 6333
            initialDelaySeconds: 20
            periodSeconds: 20
          volumeMounts:
            - name: qdrant-data
              mountPath: /qdrant/storage
  volumeClaimTemplates:
    - metadata:
        name: qdrant-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: med-rag-ebs-sc
        resources:
          requests:
            storage: 20Gi
