apiVersion: v1
kind: Service
metadata:
  name: med-rag-api-service
  namespace: med-rag
  labels:
    app.kubernetes.io/name: med-rag-api
    app.kubernetes.io/part-of: ai-korean-medi-rag
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app.kubernetes.io/name: med-rag-api
